#include "lexer.h"
#include "parser.h"
#include "semantic.h"
#include "ast_printer.h"
#include "codegen.h"
#include <iostream>
#include <fstream>
#include <cstring>

using namespace std;

void printUsage(const char* progName) {
    cerr << "Usage: " << progName << " [options] < input.bas\n";
    cerr << "Options:\n";
    cerr << "  -o <name>       Output class name (default: BasicProgram)\n";
    cerr << "  --dump-ast      Print AST and exit\n";
    cerr << "  --check-only    Parse and type-check, don't generate code\n";
    cerr << "  --bytecode      Disassemble generated bytecode (runs javap)\n";
    cerr << "  --help          Show this help\n";
}

int main(int argc, char** argv) {
    bool dumpAst = false;
    bool checkOnly = false;
    bool disassembleBytecode = false;
    string outputClassName = "BasicProgram";  // Default output class name
    
    // Parse command-line arguments
    for (int i = 1; i < argc; ++i) {
        if (strcmp(argv[i], "-o") == 0) {
            if (i + 1 < argc) {
                outputClassName = argv[++i];
            } else {
                cerr << "Error: -o requires a class name argument\n";
                printUsage(argv[0]);
                return 1;
            }
        } else if (strcmp(argv[i], "--dump-ast") == 0) {
            dumpAst = true;
        } else if (strcmp(argv[i], "--check-only") == 0) {
            checkOnly = true;
        } else if (strcmp(argv[i], "--bytecode") == 0) {
            disassembleBytecode = true;
        } else if (strcmp(argv[i], "--help") == 0) {
            printUsage(argv[0]);
            return 0;
        } else {
            cerr << "Unknown option: " << argv[i] << "\n";
            printUsage(argv[0]);
            return 1;
        }
    }
    
    try {
        // PHASE 1: Lexical Analysis and Parsing
        Lexer lexer(cin);
        Parser parser(lexer);
        Program program = parser.parse();
        
        // Store parser data for code generation
        auto userTypes = parser.getUserTypes();
        auto userClassNames = parser.getUserClassNames();
        auto knownTypes = parser.getKnownTypes();
        
        // PHASE 2: Semantic Analysis
        SemanticAnalyzer analyzer;
        
        // Initialize struct/class field types before analysis
        analyzer.initStructTypes(userTypes);
        analyzer.initClassTypesFromProgram(program);
        
        analyzer.analyze(program);
        
        // Always report semantic errors
        if (analyzer.hasErrors()) {
            cerr << "Semantic errors:\n";
            for (const auto& err : analyzer.getErrors()) {
                cerr << "  " << err << "\n";
            }
            return 1;
        }
        
        // Dump AST if requested
        if (dumpAst) {
            ASTPrinter printer(cout);
            printer.print(program);
            return 0;
        }
        
        if (checkOnly) {
            cout << "✓ Syntax and semantics OK\n";
            return 0;
        }
        
        // PHASE 3: Code Generation
        string outputFile = outputClassName + ".class";
        
        // Create ClassFile and generate bytecode
        ClassFile cf;
        cf.className = outputClassName;
        cf.buildConstantPool();
        cf.initStructs(userTypes);
        cf.generate(program.declarations, program.statements, knownTypes);
        
        // Write to file
        ofstream outFile(outputFile, ios::binary);
        if (!outFile) {
            cerr << "Error: Cannot open output file: " << outputFile << "\n";
            return 1;
        }
        cf.write(outFile);
        outFile.close();  // Ensure file is fully written
        
        cout << "Generated " << outputFile << "\n";
        
        // Disassemble bytecode if requested
        if (disassembleBytecode) {
            string bytecodeOutput = outputClassName + "_bytecode.txt";
            string javapCmd = "javap -c -p -v " + outputFile + " > " + bytecodeOutput + " 2>&1";
            int result = system(javapCmd.c_str());
            if (result == 0) {
                cout << "Bytecode disassembly written to " << bytecodeOutput << "\n";
            } else {
                cerr << "Warning: javap failed. Make sure Java/JDK is installed.\n";
            }
        }
        
        return 0;
        
    } catch (const exception& e) {
        cerr << "Error: " << e.what() << "\n";
        return 1;
    }
}

